version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
    commit-message:
      prefix: deps(github-actions)
    labels:
      - dependencies
    groups:
      actions:
        patterns:
          - "*"
