on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-node@949feb2413d6458794dcd2491c4babbbce0c15c1 # v7.1.0
        with:
          node-version: 26

      - run: npm ci
      - uses: HaaLeo/publish-vscode-extension@1b8df468b849f76a143b8c18bf0ffa2075398d12 # v2.1.0
        id: package
        with:
          pat: fake
          dryRun: true

      - uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          name: ${{ github.ref_name }}
          files: ${{ steps.package.outputs.vsixPath }}
          fail_on_unmatched_files: true
          draft: true

      - uses: HaaLeo/publish-vscode-extension@1b8df468b849f76a143b8c18bf0ffa2075398d12 # v2.1.0
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          extensionFile: ${{ steps.package.outputs.vsixPath }}
          registryUrl: https://marketplace.visualstudio.com

      - uses: HaaLeo/publish-vscode-extension@1b8df468b849f76a143b8c18bf0ffa2075398d12 # v2.1.0
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ steps.package.outputs.vsixPath }}
